BASE_CONFIG: configs/segmentation/ood/base.yaml
MODEL:
  OOD_PROJECTOR:
    TYPE: mlp
    INPUT_DIM: 768
    HIDDEN_DIM: 512
    OUTPUT_DIM: 256
    NUM_LAYERS: 3
  OOD_HEAD:
    NAME: LinearHead
    EMBEDDING_DIM: 256
    NUM_CLASSES: 2
  SEGMENTOR_CKPT: ckpts/gmm-segmentor.ckpt
