BASE_CONFIG: 'configs/segmentation/cityscapes/gmm_seg/base.yaml'
MODEL:
  BACKBONE:
    LEARNABLE_PARAMS:
      TYPE: conv_upsampling
      NUM_PRE_LINEAR_LAYERS: 1
      PRE_HIDDEN_DIM: 256
      NUM_CONV_LAYERS: 1
      CONV_HIDDEN_DIM: 256
      NUM_POST_LINEAR_LAYERS: 0
      POST_HIDDEN_DIM: 256
      OUTPUT_DIM: 256